<a href="https://colab.research.google.com/github/salonapaliwal7/KNN-without-sklearn-/blob/main/KNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [2]:
!pip install gdown==4.6.0

Collecting gdown==4.6.0
  Downloading gdown-4.6.0-py3-none-any.whl.metadata (4.4 kB)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from gdown==4.6.0) (3.25.2)
Requirement already satisfied: requests[socks] in /usr/local/lib/python3.12/dist-packages (from gdown==4.6.0) (2.32.4)
Requirement already satisfied: six in /usr/local/lib/python3.12/dist-packages (from gdown==4.6.0) (1.17.0)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from gdown==4.6.0) (4.67.3)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.12/dist-packages (from gdown==4.6.0) (4.13.5)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4->gdown==4.6.0) (2.8.3)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4->gdown==4.6.0) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests[socks]->gdown==4.6.0) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests[socks]->gdown==4.6.0) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests[socks]->gdown==4.6.0) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests[socks]->gdown==4.6.0) (2026.2.25)
Requirement already satisfied: PySocks!=1.5.7,>=1.5.6 in /usr/local/lib/python3.12/dist-packages (from requests[socks]->gdown==4.6.0) (1.7.1)
Downloading gdown-4.6.0-py3-none-any.whl (14 kB)
Installing collected packages: gdown
  Attempting uninstall: gdown
    Found existing installation: gdown 5.2.1
    Uninstalling gdown-5.2.1:
      Successfully uninstalled gdown-5.2.1
Successfully installed gdown-4.6.0

In [3]:
!gdown 1hio0ntKXvy9jZEOK2Tg0czv50zer5Kek

Downloading...
From: https://drive.google.com/uc?id=1hio0ntKXvy9jZEOK2Tg0czv50zer5Kek
To: /content/binary_class.csv
100% 9.12k/9.12k [00:00<00:00, 20.8MB/s]

In [4]:
!wget --no-check-certificate 'https://docs.google.com/uc?export=download&id=1G4_HCTrDSC0CettNnW5b1pRWmsmbs5Ax' -O binary_class.csv

--2026-04-10 03:57:29--  https://docs.google.com/uc?export=download&id=1G4_HCTrDSC0CettNnW5b1pRWmsmbs5Ax
Resolving docs.google.com (docs.google.com)... 173.194.216.138, 173.194.216.100, 173.194.216.113, ...
Connecting to docs.google.com (docs.google.com)|173.194.216.138|:443... connected.
HTTP request sent, awaiting response... 303 See Other
Location: https://drive.usercontent.google.com/download?id=1G4_HCTrDSC0CettNnW5b1pRWmsmbs5Ax&export=download [following]
--2026-04-10 03:57:29--  https://drive.usercontent.google.com/download?id=1G4_HCTrDSC0CettNnW5b1pRWmsmbs5Ax&export=download
Resolving drive.usercontent.google.com (drive.usercontent.google.com)... 172.253.147.132, 2607:f8b0:400c:c28::84
Connecting to drive.usercontent.google.com (drive.usercontent.google.com)|172.253.147.132|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 9119 (8.9K) [application/octet-stream]
Saving to: ‘binary_class.csv’

binary_class.csv    100%[===================>]   8.91K  --.-KB/s    in 0s

2026-04-10 03:57:30 (64.1 MB/s) - ‘binary_class.csv’ saved [9119/9119]

In [5]:
df=pd.read_csv('binary_class.csv')
df.head()

   Region  Fresh  Milk  Grocery  Frozen  Detergents_Paper  Delicassen  class
0       3  12669  9656     7561     214              2674        1338      2
1       3   7057  9810     9568    1762              3293        1776      2
2       3   6353  8808     7684    2405              3516        7844      2
3       3  13265  1196     4221    6404               507        1788      1
4       3  22615  5410     7198    3915              1777        5185      1

In [ ]:
df.describe()

,Region,Fresh,Milk,Grocery,Frozen,Detergents_Paper,Delicassen,class
count,267.000000,267.000000,267.00000,267.000000,267.000000,267.000000,267.000000,267.000000
mean,2.580524,16036.554307,7870.59176,11016.097378,3377.726592,4197.044944,1957.007491,1.674157
std,0.748479,14611.296512,8736.23126,11057.591796,5687.482741,5682.115327,3490.749628,0.469569
min,1.000000,18.000000,134.00000,3.000000,25.000000,3.000000,3.000000,1.000000
25%,2.000000,4553.000000,2391.00000,3258.500000,802.500000,432.500000,590.000000,1.000000
50%,3.000000,14276.000000,5921.00000,8852.000000,1691.000000,2259.000000,1282.000000,2.000000
75%,3.000000,22067.500000,9793.00000,14542.500000,3727.500000,6305.000000,2297.000000,2.000000
max,3.000000,112151.000000,73498.00000,92780.000000,60869.000000,40827.000000,47943.000000,2.000000

-> Features:
Region, Fresh, Milk, Grocery, Frozen, Detergents_Paper, Delicassen




-> Target: class (likely 1 or 2 → classification problem)


-> Scaling will be required, since input data falls under large range

In [ ]:
# Separate features and target

X = df.drop('class', axis=1)
y= df['class']

In [ ]:
# train-test split

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=100)

In [ ]:
# Scaling

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [ ]:
y_train = y_train.values
y_test = y_test.values

In [ ]:
# euclidian dist to do KNN

def euclidean_distance(x1, x2):
    return np.sqrt(np.sum((x1 - x2) ** 2))

In [ ]:
# KNN without sklearn

def KNN(X_train, y_train, x_test, k=5):
  distances = []
  for i in range(len(X_train)):
    dist = euclidean_distance(x_test,X_train[i])
    distances.append((dist, y_train[i])) # append dist and its corresponding class

  # sort distances
  distances.sort(key = lambda x:x[0]) # sort based on first value in tuple

  # pick top-K
  k_neighbors = distances[:k]

  # extract labels
  labels = [label for _, label in k_neighbors]

  # majority vote
  return max(set(labels), key=labels.count)

In [ ]:
# Predict for all data points

def predict(X_train, y_train, X_test, k=5):
    predictions = []

    for x in X_test:
        pred = KNN(X_train, y_train, x, k) # call KNN for each data point
        predictions.append(pred)
    return np.array(predictions)

In [ ]:
# find Accuracy

def accuracy(y_true, y_pred):
    return np.sum(y_true == y_pred) / len(y_true)

In [ ]:
y_pred = predict(X_train, y_train, X_test, k=5)
print("Accuracy:", accuracy(y_test, y_pred))

Accuracy: 0.9629629629629629

#LEARNINGS

Why KNN is slow ?

-> KNN loops over all data points

-> It sorts every time

-> model - stored data, no training phase

# WEIGHTED KNN AFTER DOING PCA

In [12]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

df = pd.read_csv("binary_class.csv")

X= df.drop('class', axis=1)
y= df['class']

X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.2, random_state=100)

X_train = pd.get_dummies(X_train)
X_test = pd.get_dummies(X_test)

# fills the missing columns values with 0, so there is consistency in train & test data
X_train, X_test = X_train.align(X_test, join='left', axis=1, fill_value=0)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.fit_transform(X_test)

pca = PCA(n_components=3)
X_train = pca.fit_transform(X_train)
X_test = pca.fit_transform(X_test)

In [17]:
def euclidean_dist(x1,x2):
  return np.sqrt(np.sum(x1-x2)**2)


# Weighted KNN
def weighted_knn(X_train, y_train, X_test, k=5):
  distances = []
  for i in range(len(X_train)):
    dist = euclidean_dist(X_test,X_train[i])
    distances.append((dist, y_train[i]))

  distances.sort(key=lambda x:x[0])

  k_neighbors = distances[:k]

  weights = {}

  for dist, label in k_neighbors:
    weight = (1/(dist+1e-8))

    if label in  weights:
      weights[label] +=1

    else:
      weights[label] = 1

  return max(weights, key=weights.get)

In [18]:
def predict_weighted(X_train, y_train, X_test, k=5):
    predictions = []

    for x in X_test:
        pred = weighted_knn(X_train, y_train, x, k)
        predictions.append(pred)

    return np.array(predictions)


def accuracy(y_true, y_pred):
    return np.sum(y_true == y_pred) / len(y_true)



y_pred = predict_weighted(X_train, y_train.values, X_test, k=5)

print("Accuracy:", accuracy(y_test.values, y_pred))

Accuracy: 0.7222222222222222

- Weighted KNN assumes:

  👉 closer points = more reliable

- Weighted KNN gives:

  👉 very close point → VERY high weight

🔥 Intuition

Instead of:

👉 “majority wins”

You now say:

👉 “closer neighbors matter more”



“Weighted KNN improves standard KNN by assigning higher influence to closer neighbors, reducing the impact of noisy distant points.”

# Handling missing values

In [19]:
# Using imputation

# 1 : if dataset contains missing values, use median if dataset has outliers
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(strategy="mean")

X_train = imputer.fit_transform(X_train)
X_test = imputer.transform(X_test)


# 2 : knn imputer, computes missing values, by taking mean of k nearest neighbors

from sklearn.impute import KNNImputer

imputer = KNNImputer(n_neighbors=5)

X_train = imputer.fit_transform(X_train)
X_test = imputer.transform(X_test)

#Pipeline order

Split -> Impute -> Scale -> PCA -> KNN